services:
  web:
    build: .
    ports:
      - "8001:8001"
    env_file:
      - .env_dev
      
    command: sh -c "python manage.py collectstatic --noinput && gunicorn app.wsgi:application --bind  0.0.0.0:8001"
    volumes:
      - .:/code
      - static_volume:/code/static_root
    depends_on:
      - db

    restart: always
    networks:
      - webnet

  db:
    image: postgres:15
    volumes:
      - .datosdjtnt:/var/lib/postgresql/data
    env_file:
      - .env_dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - webnet

      
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/code/static_root
    depends_on:
      - web
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  static_volume:



      